sudo: required #is required to use docker service in travis
dist: trusty

script:
  - docker --version
  - cp ./Dockerfile ./context/
  - docker build --no-cache -t node-chrome-headless context
  - docker images

deploy:
  - provider: script
    script:
      - docker --version
      - docker images
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker tag node-chrome-headless $DOCKER_TEAM/node-chrome-headless
      - docker push $DOCKER_TEAM/node-chrome-headless
    on:
      branch: master