sudo: required #is required to use docker service in travis
dist: trusty
language: generic

script: bash build.sh

deploy:
  - provider: script
    script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker tag node-chrome-headless $DOCKER_TEAM/node-chrome-headless
      - docker push $DOCKER_TEAM/node-chrome-headless
    on:
      branch: master